name: Build Multi-Arch Images

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Image Version"
        required: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_REPOSITORY: ghcr.io/gareth-conv/blockscout-astr

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_GITHUB_USERNAME }}
          password: ${{ secrets.REGISTRY_GITHUB_TOKEN }}

      - name: Enable Docker Buildx
        run: |
          jq '. + {"experimental":"enabled"}' ~/.docker/config.json > ~/.docker/config_new.json
          mv ~/.docker/config_new.json ~/.docker/config.json
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          sudo systemctl restart docker
          docker buildx create --name multi_builder
          docker buildx use multi_builder

      - name: Build linux/amd64 Image
        run: |
          docker buildx build -t ${DOCKER_REPOSITORY}:${{ github.event.inputs.version }}-amd64 --platform linux/amd64 --output=type=docker -f docker/Dockerfile .

      - name: Build linux/arm64 Image
        run: |
          docker buildx build -t ${DOCKER_REPOSITORY}:${{ github.event.inputs.version }}-arm64 --platform linux/arm64 --output=type=docker -f docker/Dockerfile .

      - name: Push Multi-Arch Images
        run: |
          docker push ${DOCKER_REPOSITORY}:${{ github.event.inputs.version }}-amd64
          docker push ${DOCKER_REPOSITORY}:${{ github.event.inputs.version }}-arm64
          docker manifest create ${DOCKER_REPOSITORY}:${{ github.event.inputs.version }} \
            ${DOCKER_REPOSITORY}:${{ github.event.inputs.version }}-amd64 \
            ${DOCKER_REPOSITORY}:${{ github.event.inputs.version }}-arm64
          docker manifest create ${DOCKER_REPOSITORY}:${{ github.event.inputs.version }} \
            ${DOCKER_REPOSITORY}:${{ github.event.inputs.version }}-amd64 \
            ${DOCKER_REPOSITORY}:${{ github.event.inputs.version }}-arm64
          docker manifest push ${DOCKER_REPOSITORY}:${{ github.event.inputs.version }}
